# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17aae4b2d145ed403d67aca7e27000ca98227421e6261d6059e6ae3b8020a0434d835beb39d030d7c37e73d556b44d295398bbb3f6e18444ff2c9dffc725f977

test:
  secret_key_base: ace636ef375d9855b01fe9d0d690d5fbaf047d6999162594c38f9b604015646426c3f56865b3d8591c45185463e96c50f579020b132806953db9cc26fb5d4b83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
